ALTER TABLE Student
ADD UserID INT UNIQUE,
ADD FOREIGN KEY (UserID)
REFERENCES UserAccount(UserID);

ALTER TABLE Manager
ADD UserID INT UNIQUE,
ADD FOREIGN KEY (UserID)
REFERENCES UserAccount(UserID);

